## Supply Chain Analysis
- The supply Chain is the network of production and logistics involved in producing and delivering goods to customers. And Supply Chain Analysis means analyzing various components of a Supply Chain to understand how to improve the effectiveness of the Supply Chain to create more value for customers.

## What is supply chain analysis?
- Supply chain analysis is the process of evaluating every stage of a supply chain starting from the time the business acquires raw materials or supplies from its suppliers to the delivery of final products to the customers. 

- The purpose of the analysis is to determine which part of the supplyu chain can be improved or shortened to deliver the product more quickly and efficiently to the customers. 


## What are supply chain analytics and it's different types? 
- Each of these supply chain analytics can increase the overall efficiency of business operations, which can lead to sizable cost savings. 

1. Descriptive Analytics focuses on understanding waht happend in the past by analzing historical data. It can provide insights on key performance metrics, such as inventory levels, lead times, and delivery performance. Descriptive analytics can help identify patterns and trends in past supply chain operations, allowing organizations to make informed decision about future strategies. 

2. Diagnostic Analytics goes beyond descriptive analytics by identifying the root causes of supply chain issues. By analyzing data from different sources, such as suppliers, logistics providers, and customers, organizations can identify the factors that contribute to delays, disruptions, or quality issues in their supply chain. This can help them take corrective actions to prevent similar problems from happening in the future. 

3. Predictive Analytics uses statistical model and machine learning algorithms to forecast future supply chain events. By analyzing historical data, organization can identify patterns and trends that can help predict demand, inventory levels, and delivery performance. This can help organizations optimize their supply chain operations, reduce costs, and imporve customer satisfaction. 

4. Prescriptive Analytics takes predictive analytics one step further by providing recommendation on how to optimize supply chain operations. By using optimization algorithms and simulations, prescriptive analytics can help organizations identify the best course of action to improve supply chain performance. This can help organization make better decisions and improve their overall chain efficiency. 


## How to conduct Supply Chain analysis
- The above analytics should be used when conducting supply chain analysis. The basic steps of an analysis are:
    - Define your objectives 
    - Research the market. 
    - identify key market indicators 
    - Pull together your findings and outline final suggestions - I'd recommend taking a look at using SharpCloud as a visual presentation tool. 


## DataSet¶
- Here is a dataset we collected from a Fashion and Beauty startup. The dataset is based on the supply chain of Makeup products. Below are all the features in the dataset:

- Product Type
- SKU
- Price
- Availability
- Number of products sold
- Revenue generated
- Customer demographics
- Stock levels
- Lead times
- Order quantities
- Shipping times
- Shipping carriers
- Shipping costs
- Supplier name
- Location
- Lead time
- Production volumes
- Manufacturing lead time
- Manufacturing costs
- Inspection results
- Defect rates
- Transportation modes
- Routes
- Costs

## Import Libraries

In [37]:
import pandas as pd 
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.renderers.default = "notebook"
pio.renderers.default = "notebook_connected"

## Read Data

In [11]:
data = pd.read_csv('supply_chain_data.csv')

In [12]:
data.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Product type             100 non-null    object
 1   SKU                      100 non-null    object
 2   Price                    100 non-null    float64
 3   Availability             100 non-null    int64
 4   Number of products sold  100 non-null    int64
 5   Revenue generated        100 non-null    float64
 6   Customer demographics    100 non-null    object
 7   Stock levels             100 non-null    int64
 8   Lead times               100 non-null    int64
 9   Order quantities         100 non-null    int64
 10  Shipping times           100 non-null    int64
 11  Shipping carriers        100 non-null    object
 12  Shipping costs           100 non-null    float64
 13  Supplier name            100 non-null    object
 14  Location                 100 non-null    object
 15  Lead time                100 non-null    int64
 16  Production volumes       100 non-null    int64
 17  Manufacturing lead time  100 non-null    int64
 18  Manufacturing costs      100 non-null    float64
 19  Inspection results       100 non-null    object
 20  Defect rates             100 non-null    float64
 21  Transportation modes     100 non-null    object
 22  Routes                   100 non-null    object
 23  Costs                    100 non-null    float64
dtypes: float64(6), int64(9), object(9)
memory usage: 18.9+ KB

In [14]:
data.isnull().sum()

Product type               0
SKU                        0
Price                      0
Availability               0
Number of products sold    0
Revenue generated          0
Customer demographics      0
Stock levels               0
Lead times                 0
Order quantities           0
Shipping times             0
Shipping carriers          0
Shipping costs             0
Supplier name              0
Location                   0
Lead time                  0
Production volumes         0
Manufacturing lead time    0
Manufacturing costs        0
Inspection results         0
Defect rates               0
Transportation modes       0
Routes                     0
Costs                      0
dtype: int64

No null values present in our dataset

## Descriptive Statistics

In [15]:
data.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239831,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976921,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

## Product type and Price 
- analyzing the Supply Chain by looking at the relationship between the price of the products and the revenue generated by them.

In [16]:
data.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [17]:
data['Product type'].unique()

array(['haircare', 'skincare', 'cosmetics'], dtype=object)

In [18]:
data['Number of products sold'].unique()

array([802, 736,   8,  83, 871, 147,  65, 426, 150, 980, 996, 960, 336,
       249, 562, 469, 280, 126, 620, 187, 320, 601, 884, 391, 209, 142,
       353, 352, 394, 253, 327, 168, 781, 616, 602, 449, 963, 705, 176,
       933, 556, 155, 598, 919,  24, 859, 910,  29,  99, 633, 154, 820,
       242, 622, 701,  93, 227, 896, 484, 380, 117, 270, 246, 134, 457,
       704, 513, 163, 511,  32, 637, 478, 375, 904, 106, 241, 359, 946,
       198, 872, 774, 663, 618,  25, 223,  79, 737, 916, 276, 114, 987,
       672, 324,  62, 913, 627])

In [26]:
fig = px.scatter(data, x='Price', y = 'Revenue generated', color='Product type', hover_data='Number of products sold', trendline='ols',)

In [38]:
import plotly.express as px

fig = px.scatter(
    data, 
    x='Price', 
    y='Revenue generated', 
    color='Product type', 
    hover_data=['Number of products sold'], 
    trendline='ols'
)

fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [31]:
!pip install --upgrade plotly nbformat ipywidgets

Requirement already satisfied: plotly in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (6.3.0)
Requirement already satisfied: nbformat in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (5.10.4)
Collecting ipywidgets
  Using cached ipywidgets-8.1.7-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: narwhals>=1.15.1 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from plotly) (1.44.0)
Requirement already satisfied: packaging in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from plotly) (25.0)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from nbformat) (4.24.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: comm>=0.1.3 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipywidgets) (9.3.0)
Collecting widgetsnbextension~=4.0.14 (from ipywidgets)
  Using cached widgetsnbextension-4.0.14-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab_widgets~=3.0.15 (from ipywidgets)
  Using cached jupyterlab_widgets-3.0.15-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: decorator in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.51)
Requirement already satisfied: pygments>=2.4.0 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: attrs>=22.2.0 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (0.25.1)
Requirement already satisfied: platformdirs>=2.5 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.8)
Requirement already satisfied: ptyprocess>=0.5 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: executing>=1.2.0 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure-eval in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)
Using cached ipywidgets-8.1.7-py3-none-any.whl (139 kB)
Using cached jupyterlab_widgets-3.0.15-py3-none-any.whl (216 kB)
Using cached widgetsnbextension-4.0.14-py3-none-any.whl (2.2 MB)
Installing collected packages: widgetsnbextension, jupyterlab_widgets, ipywidgets
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [ipywidgets]
Successfully installed ipywidgets-8.1.7 jupyterlab_widgets-3.0.15 widgetsnbextension-4.0.14

In [32]:
!pip install statsmodels

Requirement already satisfied: statsmodels in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (0.14.5)
Requirement already satisfied: numpy<3,>=1.22.3 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from statsmodels) (2.3.1)
Requirement already satisfied: scipy!=1.9.2,>=1.8 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from statsmodels) (1.16.0)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from statsmodels) (2.3.0)
Requirement already satisfied: patsy>=0.5.6 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from statsmodels) (1.0.1)
Requirement already satisfied: packaging>=21.3 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from statsmodels) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.17.0)

In [39]:
!pip install --upgrade nbformat

Requirement already satisfied: nbformat in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (5.10.4)
Requirement already satisfied: fastjsonschema>=2.15 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from nbformat) (2.21.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from nbformat) (4.24.0)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from nbformat) (5.8.1)
Requirement already satisfied: traitlets>=5.1 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from nbformat) (5.14.3)
Requirement already satisfied: attrs>=22.2.0 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (25.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (2025.4.1)
Requirement already satisfied: referencing>=0.28.4 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jsonschema>=2.6->nbformat) (0.25.1)
Requirement already satisfied: platformdirs>=2.5 in /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages (from jupyter-core!=5.0.*,>=4.12->nbformat) (4.3.8)

In [40]:
import plotly.express as px
fig = px.scatter(x=[1,2,3], y=[4,5,6])
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [41]:
import sys
!{sys.executable} -m pip show nbformat

Name: nbformat
Version: 5.10.4
Summary: The Jupyter Notebook format
Home-page: https://jupyter.org
Author:
Author-email: Jupyter Development Team <jupyter@googlegroups.com>
License: BSD 3-Clause License

- Copyright (c) 2001-2015, IPython Development Team
- Copyright (c) 2015-, Jupyter Development Team

All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Location: /Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages
Requires: fastjsonschema, jsonschema, jupyter-core, traitlets
Required-by:

In [42]:
!{sys.executable} -m pip install nbformat>=4.2.0

zsh:1: 4.2.0 not found