In [ ]:

import pandas as pd

In [5]:
data = pd.read_csv('supply_chain_data.csv')

In [6]:
data.head()

,Product type,SKU,Price,Availability,Number of products sold,Revenue generated,Customer demographics,Stock levels,Lead times,Order quantities,...,Location,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Inspection results,Defect rates,Transportation modes,Routes,Costs
0,haircare,SKU0,69.808006,55,802,8661.996792,Non-binary,58,7,96,...,Mumbai,29,215,29,46.279879,Pending,0.226410,Road,Route B,187.752075
1,skincare,SKU1,14.843523,95,736,7460.900065,Female,53,30,37,...,Mumbai,23,517,30,33.616769,Pending,4.854068,Road,Route B,503.065579
2,haircare,SKU2,11.319683,34,8,9577.749626,Unknown,1,10,88,...,Mumbai,12,971,27,30.688019,Pending,4.580593,Air,Route C,141.920282
3,skincare,SKU3,61.163343,68,83,7766.836426,Non-binary,23,13,59,...,Kolkata,24,937,18,35.624741,Fail,4.746649,Rail,Route A,254.776159
4,skincare,SKU4,4.805496,26,871,2686.505152,Non-binary,5,3,56,...,Delhi,5,414,3,92.065161,Fail,3.145580,Air,Route A,923.440632

In [39]:
data['Costs'].value_counts()

Costs
187.752075    1
687.286178    1
866.472800    1
677.944570    1
405.167068    1
             ..
880.080988    1
764.935376    1
123.437028    1
762.459182    1
210.743009    1
Name: count, Length: 100, dtype: int64

In [7]:
data.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

## Product Performance 
- Product performance tell you hwo well each product (or SKU) is selling. It's basically about **demand** and **sales volume**

**Why we look for this:**
- To identify **best-sellers** (SKUs that drive business).
- To identify **low-performance products** (which might need discounting, marketing push, or even removal)
- To track **inventory alignment**(We are stocking the right products?).

**Beyond basic analysis, you can also check:**
- **Seasonality:** Do some products sell more in certain months/seasons?
- **Profitability:** Not just which products sell the most, but which bring the most **Profit**(high-margin SKUs)
- **Trend analysis:** Are some products gaining or losing popularity over time?

In [ ]:
data['Number of products sold']

In [13]:
sku_sales = data.groupby('SKU')['Number of products sold'].sum().reset_index()
sku_sales = sku_sales.sort_values(by='Number of products sold', ascending=False)

#### Top 10 best seller

In [15]:
sku_sales.head(10)

      SKU  Number of products sold
2   SKU10                      996
94  SKU94                      987
89   SKU9                      980
30  SKU36                      963
31  SKU37                      963
3   SKU11                      960
76  SKU78                      946
35  SKU40                      933
39  SKU44                      919
91  SKU91                      916

#### Top 10 least seller

In [16]:
sku_sales.tail(10)

      SKU  Number of products sold
52  SKU56                       93
23   SKU3                       83
86  SKU87                       79
56   SKU6                       65
97  SKU97                       62
68  SKU70                       32
43  SKU48                       29
84  SKU85                       25
40  SKU45                       24
12   SKU2                        8

In [ ]:
data['Product type']

In [18]:
product_performance = data.groupby('Product type')['Number of products sold'].sum().reset_index()
product_performance = product_performance.sort_values(by='Number of products sold', ascending=False)

In [19]:
product_performance

  Product type  Number of products sold
2     skincare                    20731
1     haircare                    13611
0    cosmetics                    11757