## Supply Chain Analysis
- The supply Chain is the network of production and logistics involved in producing and delivering goods to customers. And Supply Chain Analysis means analyzing various components of a Supply Chain to understand how to improve the effectiveness of the Supply Chain to create more value for customers.

## What is supply chain analysis?
- Supply chain analysis is the process of evaluating every stage of a supply chain starting from the time the business acquires raw materials or supplies from its suppliers to the delivery of final products to the customers. 

- The purpose of the analysis is to determine which part of the supplyu chain can be improved or shortened to deliver the product more quickly and efficiently to the customers. 


## What are supply chain analytics and it's different types? 
- Each of these supply chain analytics can increase the overall efficiency of business operations, which can lead to sizable cost savings. 

1. Descriptive Analytics focuses on understanding waht happend in the past by analzing historical data. It can provide insights on key performance metrics, such as inventory levels, lead times, and delivery performance. Descriptive analytics can help identify patterns and trends in past supply chain operations, allowing organizations to make informed decision about future strategies. 

2. Diagnostic Analytics goes beyond descriptive analytics by identifying the root causes of supply chain issues. By analyzing data from different sources, such as suppliers, logistics providers, and customers, organizations can identify the factors that contribute to delays, disruptions, or quality issues in their supply chain. This can help them take corrective actions to prevent similar problems from happening in the future. 

3. Predictive Analytics uses statistical model and machine learning algorithms to forecast future supply chain events. By analyzing historical data, organization can identify patterns and trends that can help predict demand, inventory levels, and delivery performance. This can help organizations optimize their supply chain operations, reduce costs, and imporve customer satisfaction. 

4. Prescriptive Analytics takes predictive analytics one step further by providing recommendation on how to optimize supply chain operations. By using optimization algorithms and simulations, prescriptive analytics can help organizations identify the best course of action to improve supply chain performance. This can help organization make better decisions and improve their overall chain efficiency. 


## How to conduct Supply Chain analysis
- The above analytics should be used when conducting supply chain analysis. The basic steps of an analysis are:
    - Define your objectives 
    - Research the market. 
    - identify key market indicators 
    - Pull together your findings and outline final suggestions - I'd recommend taking a look at using SharpCloud as a visual presentation tool. 


## DataSet¶
- Here is a dataset we collected from a Fashion and Beauty startup. The dataset is based on the supply chain of Makeup products. Below are all the features in the dataset:

- Product Type
- SKU
- Price
- Availability
- Number of products sold
- Revenue generated
- Customer demographics
- Stock levels
- Lead times
- Order quantities
- Shipping times
- Shipping carriers
- Shipping costs
- Supplier name
- Location
- Lead time
- Production volumes
- Manufacturing lead time
- Manufacturing costs
- Inspection results
- Defect rates
- Transportation modes
- Routes
- Costs

## Import Libraries

In [24]:
import pandas as pd
import plotly.express as px
import plotly.io as pio
import plotly.graph_objects as go
pio.templates.default = "plotly_white"

## Read Data

In [ ]:
data = pd.read_csv('supply_chain_data.csv')

Fashion.ipynb         Fashions.ipynb        supply_chain_data.csv

## Descriptive Statistics

In [7]:
data.describe()

,Price,Availability,Number of products sold,Revenue generated,Stock levels,Lead times,Order quantities,Shipping times,Shipping costs,Lead time,Production volumes,Manufacturing lead time,Manufacturing costs,Defect rates,Costs
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000
mean,49.462461,48.400000,460.990000,5776.048187,47.770000,15.960000,49.220000,5.750000,5.548149,17.080000,567.840000,14.77000,47.266693,2.277158,529.245782
std,31.168193,30.743317,303.780074,2732.841744,31.369372,8.785801,26.784429,2.724283,2.651376,8.846251,263.046861,8.91243,28.982841,1.461366,258.301696
min,1.699976,1.000000,8.000000,1061.618523,0.000000,1.000000,1.000000,1.000000,1.013487,1.000000,104.000000,1.00000,1.085069,0.018608,103.916248
25%,19.597823,22.750000,184.250000,2812.847151,16.750000,8.000000,26.000000,3.750000,3.540248,10.000000,352.000000,7.00000,22.983299,1.009650,318.778455
50%,51.239831,43.500000,392.500000,6006.352023,47.500000,17.000000,52.000000,6.000000,5.320534,18.000000,568.500000,14.00000,45.905622,2.141863,520.430444
75%,77.198228,75.000000,704.250000,8253.976921,73.000000,24.000000,71.250000,8.000000,7.601695,25.000000,797.000000,23.00000,68.621026,3.563995,763.078231
max,99.171329,100.000000,996.000000,9866.465458,100.000000,30.000000,96.000000,10.000000,9.929816,30.000000,985.000000,30.00000,99.466109,4.939255,997.413450

In [6]:
fig = px.scatter(data, x='Price', y = 'Revenue generated', color='Product type', hover_data='Number of products sold', trendline='ols',)
fig.show()

## Sales by Product Type
- The company derives more revenue from skincare products, and the higher the price of skincare products, the more revenue they generate. Now let's have a look at the sales by product type;

In [8]:
data['Product type'].value_counts()

Product type
skincare     40
haircare     34
cosmetics    26
Name: count, dtype: int64

In [10]:
data['Number of products sold'].value_counts()

Number of products sold
336    2
320    2
134    2
963    2
246    1
      ..
168    1
327    1
253    1
394    1
627    1
Name: count, Length: 96, dtype: int64

(100, 24)

In [9]:
data.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [16]:
sales_data = data.groupby('Product type')['Number of products sold'].sum().reset_index()
pie_chart = px.pie(sales_data, values='Number of products sold', names='Product type', 
                   title='Sales by Product Type', 
                   hover_data=['Number of products sold'], 
                   hole=0.5, 
                   color_discrete_sequence=px.colors.qualitative.Pastel)
pie_chart.update_traces(textposition='inside', textinfo='percent+label')
pie_chart.show()

**So 45% of the business comes from skincare products, 29.5% from haircare, and 25.5% from cosmetics.**

## Total Revenue by Shipping Carrier

In [17]:
data.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [18]:
data['Revenue generated']

0     8661.996792
1     7460.900065
2     9577.749626
3     7766.836426
4     2686.505152
         ...
95    7386.363944
96    7698.424766
97    4370.916580
98    8525.952560
99    9185.185829
Name: Revenue generated, Length: 100, dtype: float64

In [20]:
data['Shipping carriers'].value_counts()

Shipping carriers
Carrier B    43
Carrier C    29
Carrier A    28
Name: count, dtype: int64

In [25]:
total_revenue = data.groupby('Shipping carriers')['Revenue generated'].sum().reset_index()
fig = go.Figure()

fig.add_trace(go.Bar(x=total_revenue['Shipping carriers'], 
                     y = total_revenue['Revenue generated']))

fig.update_layout(title="Total Revenue by Shipping Carrier", 
                  xaxis_title = 'Shipping Carrier', 
                  yaxis_title = 'Total Revenue')

fig.show()

In [22]:
total_revenue

  Shipping carriers  Revenue generated
0         Carrier A      142629.994607
1         Carrier B      250094.646988
2         Carrier C      184880.177143

In [13]:
sales_data

  Product type  Number of products sold
0    cosmetics                    11757
1     haircare                    13611
2     skincare                    20731

## Product type 
- The company in using three carriers for transportation, and Carrier B helps the company in generating more revenue. Now let's have a look at the the Average lead time and Average Manufacturing Costs for all products of the company.

In [32]:
avg_lead_time = data.groupby('Product type')['Lead time'].mean().reset_index()
avg_manufacturing_costs = data.groupby('Product type')['Manufacturing costs'].mean().reset_index()

results = pd.merge(avg_lead_time, avg_manufacturing_costs, on='Product type')

results.rename(columns={'Lead time': 'Average Lead Time', 'Manufacturing costs': 'Average Manufacturing Costs'}, inplace=True)
print(results)

  Product type  Average Lead Time  Average Manufacturing Costs
0    cosmetics          13.538462                    43.052740
1     haircare          18.705882                    48.457993
2     skincare          18.000000                    48.993157

In [31]:
print(avg_lead_time)
print(avg_manufacturing_costs)

  Product type  Lead time
0    cosmetics  13.538462
1     haircare  18.705882
2     skincare  18.000000
  Product type  Manufacturing costs
0    cosmetics            43.052740
1     haircare            48.457993
2     skincare            48.993157

## Analyzing SKUs 
- There's a column in the dataset as SKUs. you must have heard it for the very first time. So, SKU stands for Stock Keeping Units. They're like special codes that help companies keep track of all the different things they have for sale. Imagine you have a large toy store with lots of toys. Each toy is different and has its name and price but when you want to know how many you have left, you need a way to identify them. so you give each toy a unique code, like a secret number only the store knows. This secret number is called SKU.

## Revenue generated by SKU

In [33]:
revenue_chart = px.line(data, x='SKU', 
                        y='Revenue generated', 
                        title='Revenue Generated by SKU')
revenue_chart.show()

## Stock Levels by SKU
- Stock levels refer to the number of products a store or business has in its inventory. Now let's have a look at the stock levels of each SKU:

In [34]:
stock_chart = px.line(data, x="SKU", 
                      y='Stock levels', 
                      title='Stock Levels by SKU')
stock_chart.show()

## Order Quantity by SKU

In [35]:
order_quantity_chart = px.bar(data, x='SKU', 
                              y='Order quantities', 
                              title='Order Quantity by SKU')
order_quantity_chart.show()

## Shipping Costs by carrier

In [36]:
shipping_cost_chart = px.bar(data, x='Shipping carriers', y='Shipping costs', 
                             title='Shipping Costs by Carrier')
shipping_cost_chart.show()

**In one of the above visualizations, we discovered that Carrier B helps the company in more revenue. It is also the most costly Carrier among the three**

### Cost Distribution by Transportation Mode

In [37]:
transportation_chart = px.pie(data, values='Costs', 
                              names='Transportation modes', 
                              title='Cost Distribution by Transportation Mode',
                              hole=0.5,
                              color_discrete_sequence=px.colors.qualitative.Pastel)

transportation_chart.show()

**So the company spends more on Road and Rail modes of transportation for the transportation of Goods.**

## Analyzing Defect Rate 
- The defect rate in the supply chain refers to the percentage of products that have somenting wrong or are found broken after shipping. 

## Average Defect Rates by Product type

In [41]:
data.columns

Index(['Product type', 'SKU', 'Price', 'Availability',
       'Number of products sold', 'Revenue generated', 'Customer demographics',
       'Stock levels', 'Lead times', 'Order quantities', 'Shipping times',
       'Shipping carriers', 'Shipping costs', 'Supplier name', 'Location',
       'Lead time', 'Production volumes', 'Manufacturing lead time',
       'Manufacturing costs', 'Inspection results', 'Defect rates',
       'Transportation modes', 'Routes', 'Costs'],
      dtype='object')

In [43]:
defect_rates_by_product = data.groupby('Product type')['Defect rates'].mean().reset_index()

fig = px.bar(defect_rates_by_product, x='Product type', y='Defect rates',
             title='Average Defect Rates by Product Type')

fig.show()

**So the defect rate of haircare products is higher**

## Defect Rates by Transportation Mode

In [44]:
pivot_table = pd.pivot_table(data, values='Defect rates', 
                             index=['Transportation modes'], 
                             aggfunc='mean')

transportation_chart = px.pie(values=pivot_table['Defect rates'],
                              names=pivot_table.index, 
                              title='Defect Rates by Transportation Mode',
                              hole=0.5,
                              color_discrete_sequence=px.colors.qualitative.Pastel)

transportation_chart.show()

In [45]:
pivot_table

                      Defect rates
Transportation modes
Air                       1.823924
Rail                      2.318814
Road                      2.620938
Sea                       2.315281

**Road transportation results in a higher defect rate, and Air transportation has the lowest defact rate.**


## Summary 
- Supply Chain Analysis means analyzing various components of a Supply Chain to understand how to improve the effectiveness of the Supply Chain to create more value for customers.