In [1]:
import numpy as np
import pandas as pd
import re

In [2]:
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv('gurgaon_properties_cleaned_v1.csv')

In [4]:
df.duplicated().sum()

122

In [5]:
df.head(1)

,property_type,society,sector,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,floorNum,facing,agePossession,nearbyLocations,furnishDetails,features
0,flat,signature andour heights,sector 71,0.39,9846.0,396.0,Super Built up area 325(30.19 sq.m.),1.0,1.0,2,not available,1.0,NaN,0 to 1 Year Old,"['Bigbasket SPR 5K DS', 'iON Digital Zone, DPGITM', 'NH8', 'Toll Plaza', 'DPG Institute of Technology and Mgmt', 'ICICI BANK ATM', 'Park Hospital Sohna Rd', 'IGI Airport', 'HDFC Bank, Sec 59', 'Grey Orange (India), NH8', 'Tata Projects Limited Sector 71', 'NIIT, Confluence Building', 'Candor TechSpace, Sec 48', 'TATA Workshop Gurgaon - Zedex Mobility', 'IGL CNG Pump Sec 48']",[],NaN

In [6]:
# focus is on -> areaWithType, additionalRoom, agePossession, furnishDetails, features

## areaWithType

In [7]:
df['areaWithType'].isnull().sum()

1

In [8]:
df = df.dropna(subset=['areaWithType'])

In [9]:
df.columns

Index(['property_type', 'society', 'sector', 'price', 'price_per_sqft', 'area',
       'areaWithType', 'bedRoom', 'bathroom', 'balcony', 'additionalRoom',
       'floorNum', 'facing', 'agePossession', 'nearbyLocations',
       'furnishDetails', 'features'],
      dtype='object')

In [10]:
df['areaWithType'].isnull().sum()

0

In [11]:
df.sample(5)[['price', 'area', 'areaWithType']]

,price,area,areaWithType
3419,1.40,2262.0,Super Built up area 2262(210.15 sq.m.)Built Up area: 1854 sq.ft. (172.24 sq.m.)Carpet area: 1576 sq.ft. (146.42 sq.m.)
490,2.50,2450.0,Carpet area: 2450 (227.61 sq.m.)
2815,0.85,685.0,Carpet area: 685 (63.64 sq.m.)
2622,0.80,900.0,Plot area 900(83.61 sq.m.)Built Up area: 900 sq.ft. (83.61 sq.m.)
2250,2.20,1968.0,Super Built up area 2812(261.24 sq.m.)Built Up area: 2390 sq.ft. (222.04 sq.m.)Carpet area: 1968 sq.ft. (182.83 sq.m.)

In [12]:
text = "Super Built up area 1351(125.51 sq.m.)"
match = re.search(r'Super Built up area (\d+\.?\d*)', text)
if match:
    print(float(match.group(1)))

1351.0

In [13]:
# This function extracts the Super Built up area
def get_super_built_up_area(text):
    match = re.search(r'Super Built up area (\d+\.?\d*)', text)
    if match:
        return float(match.group(1))
    return None

In [14]:
# This function extracts the Built Up area or Carpet area
def get_area(text, area_type):
    match = re.search(area_type + r'\s*:\s*(\d+\.?\d*)', text)
    if match:
        return float(match.group(1))
    return None

In [15]:
# This function checks if the area is provided in sq.m. and converts it to sqft if needed
def convert_to_sqft(text, area_value):
    if area_value is None:
        return None
    match = re.search(r'{} \((\d+\.?\d*) sq.m.\)'.format(area_value), text)
    if match:
        sq_m_value = float(match.group(1))
        return sq_m_value * 10.7639  # conversion factor from sq.m. to sqft
    return area_value

In [16]:
## This function works when you Null values in your dataset. 

# import math
# def convert_to_sqft(raw_text, area_value):
#     if not isinstance(raw_text, str):
#         return area_value
    
#     if area_value is None or (isinstance(area_value, float) and math.isnan(area_value)):
#         return None

#     pattern = rf'{int(area_value)}\s*\((\d+\.?\d*)\s*sq\.m\.\)'
#     match = re.search(pattern, raw_text)

#     if match:
#         sqm = float(match.group(1))
#         return sqm * 10.7639
    
#     return area_value

In [17]:
# Extract Super Built up area and convert to sqft if needed
df['super_built_up_area'] = df['areaWithType'].apply(get_super_built_up_area)
df['super_built_up_area_sqft'] = df.apply(
    lambda row: convert_to_sqft(row['areaWithType'], row['super_built_up_area']),
    axis=1
)

In [18]:
# Extract Built Up area and convert to sqft if needed
df['built_up_area'] = df['areaWithType'].apply(lambda x: get_area(x, 'Built Up area'))
df['built_up_area'] = df.apply(lambda x: convert_to_sqft(x['areaWithType'], x['built_up_area']), axis=1)

In [19]:
# Extract Carpet area and convert to sqft if needed
df['carpet_area'] = df['areaWithType'].apply(lambda x: get_area(x, 'Carpet area'))
df['carpet_area'] = df.apply(lambda x: convert_to_sqft(x['areaWithType'], x['carpet_area']), axis=1)

In [20]:
df['super_built_up_area'].isnull().sum()

1887

In [21]:
df['super_built_up_area']

0         325.00
1            NaN
2            NaN
3            NaN
4            NaN
5            NaN
6        3130.00
7            NaN
8            NaN
9        1545.00
10           NaN
11           NaN
12       1735.00
13           NaN
14           NaN
15           NaN
16       1970.00
17       1270.00
18           NaN
19           NaN
20       1975.00
21           NaN
22        650.00
23           NaN
24       1875.00
25       1640.00
26       1748.87
27           NaN
28       1350.00
29       2450.00
30           NaN
31           NaN
32       2191.00
33           NaN
34           NaN
35       1320.00
36           NaN
37       1380.00
38           NaN
39           NaN
40       1950.00
41           NaN
42       2225.00
43           NaN
44           NaN
45           NaN
46       1056.58
47           NaN
48           NaN
49           NaN
50        567.00
51       1711.00
52        950.00
53       1457.00
54       1507.00
55           NaN
56        525.00
57       2368.00
58           NaN
59       1579.00
60       2800.00
61       2950.00
62       1590.00
63       4857.00
64       2150.00
65           NaN
66       1805.00
67           NaN
68       1650.00
69           NaN
70       1650.00
71       2200.00
72       1997.00
73           NaN
74       1638.00
75           NaN
76       1239.00
77       1350.00
78           NaN
79           NaN
80       2408.00
81       2003.00
82       2905.00
83       4739.00
84       1550.00
85           NaN
86       1275.00
87       1650.00
88           NaN
89       1620.00
90           NaN
91       1400.00
92       1910.00
93       1500.00
94       1616.00
95           NaN
96       1930.00
97           NaN
98           NaN
99       1997.00
100          NaN
101      1361.00
102      1000.00
103          NaN
104      1942.00
105      2100.00
106          NaN
107      1799.00
108          NaN
109      1433.00
110      1430.00
111      1828.00
112          NaN
113          NaN
114          NaN
115      1295.00
116      1423.00
117          NaN
118          NaN
119          NaN
120      1407.00
121      2400.00
122          NaN
123      1777.00
124          NaN
125      2408.00
126          NaN
127          NaN
128          NaN
129      1743.00
130          NaN
131      2217.00
132          NaN
133          NaN
134          NaN
135      1950.00
136          NaN
137          NaN
138          NaN
139      2217.00
140      1245.00
141       567.00
142          NaN
143      1538.00
144          NaN
145          NaN
146      1745.00
147      2160.00
148          NaN
149          NaN
150       633.00
151      1100.00
152      1450.00
153      4200.00
154          NaN
155      1336.00
156          NaN
157      1099.00
158      2162.00
159          NaN
160          NaN
161          NaN
162      1578.00
163      1340.00
164          NaN
165          NaN
166          NaN
167      1865.00
168      3400.00
169      2660.00
170      1000.00
171          NaN
172          NaN
173          NaN
174      2779.00
175          NaN
176      2545.00
177          NaN
178      1262.00
179      1325.00
180          NaN
181          NaN
182          NaN
183      1811.00
184          NaN
185          NaN
186          NaN
187          NaN
188          NaN
189          NaN
190      1650.00
191      1755.00
192          NaN
193          NaN
194          NaN
195      1950.00
196      1956.00
197      2000.00
198          NaN
199          NaN
200      1465.00
201      1745.00
202      1310.00
203          NaN
204          NaN
205      2443.00
206      2585.00
207      1745.00
208          NaN
209      2425.00
210          NaN
211      1572.00
212      3246.00
213      2125.00
214          NaN
215          NaN
216          NaN
217      1640.00
218      1702.00
219          NaN
220      1200.00
221      1630.00
222      1870.00
223          NaN
224      2450.00
225      3395.00
226          NaN
227      1516.00
228          NaN
229      1825.00
230      1578.00
231          NaN
232          NaN
233          NaN
234      2343.00
235          NaN
236          NaN
237      3055.00
238          NaN
239          NaN
240          NaN
241          NaN
242      1700.00
243          NaN
244          NaN
245          NaN
246      1538.00
247          NaN
248      2802.00
249      4848.00
250      1261.00
251      1524.00
252      1852.00
253          NaN
254          NaN
255          NaN
256      1800.00
257      1579.00
258      1832.00
259      2150.00
260          NaN
261          NaN
262          NaN
263          NaN
264      1572.00
265      1760.00
266          NaN
267      2217.00
268          NaN
269          NaN
270          NaN
271      3192.00
272          NaN
273      2630.00
274          NaN
275          NaN
276          NaN
277      1647.00
278          NaN
279          NaN
280      1822.00
281      1568.00
282          NaN
283      2040.00
284      1650.00
285      1365.00
286      2875.00
287          NaN
288          NaN
289      1579.00
290          NaN
291      2403.00
292      1900.00
293          NaN
294          NaN
295      1630.00
296       750.00
297      1930.00
298          NaN
299      1406.00
300          NaN
301          NaN
302          NaN
303      1666.00
304          NaN
305          NaN
306      2095.00
307      1852.00
308      2150.00
309      1380.00
310      1660.00
311          NaN
312          NaN
313      1655.00
314      2150.00
315          NaN
316          NaN
317          NaN
318       626.00
319          NaN
320      2408.00
321          NaN
322      1099.00
323      1811.00
324      2018.00
325          NaN
326      1381.00
327      1950.00
328       600.00
329      1931.00
330          NaN
331      2588.00
332          NaN
333          NaN
334      1415.00
335          NaN
336      2905.00
337      1067.00
338          NaN
339      1608.00
340      1400.00
341      2779.00
342      1415.00
343      1103.00
344      2010.00
345      1549.00
346          NaN
347          NaN
348          NaN
349          NaN
350      1326.00
351          NaN
352          NaN
353          NaN
354          NaN
355          NaN
356          NaN
357          NaN
358      1920.00
359          NaN
360          NaN
361      1976.00
362      2003.00
363          NaN
364          NaN
365          NaN
366          NaN
367      1578.00
368          NaN
369          NaN
370      1081.00
371          NaN
372          NaN
373          NaN
374          NaN
375          NaN
376          NaN
377      1198.00
378      2727.00
379      1508.26
380          NaN
381          NaN
382      1811.00
383      2215.00
384          NaN
385      1285.00
386          NaN
387      1500.00
388      1811.00
389      2072.90
390          NaN
391      1620.00
392      2400.00
393      1000.00
394          NaN
395      1300.00
396      1660.00
397      2585.00
398          NaN
399      1700.00
400      3950.00
401      1650.00
402      1350.00
403      1998.00
404          NaN
405      1741.00
406      2690.00
407      1770.00
408      1500.00
409      3731.00
410          NaN
411          NaN
412      1640.00
413      2364.00
414      1310.00
415      1918.00
416      2358.00
417          NaN
418          NaN
419      1300.00
420      1963.00
421      2385.00
422      1640.00
423          NaN
424          NaN
425      2411.00
426          NaN
427      2950.00
428          NaN
429          NaN
430          NaN
431          NaN
432      2341.00
433      2812.00
434      1245.00
435          NaN
436      1554.00
437      1943.00
438          NaN
439      2000.00
440      2295.00
441          NaN
442          NaN
443      1480.00
444          NaN
445      1930.00
446          NaN
447          NaN
448          NaN
449      1383.00
450      1485.00
451      2000.00
452      2408.00
453          NaN
454          NaN
455          NaN
456      2149.00
457      2132.00
458      2361.00
459      1755.00
460      1660.00
461      1744.00
462          NaN
463      1230.00
464      1930.00
465      1751.00
466      1700.00
467          NaN
468          NaN
469      1457.00
470          NaN
471      2191.00
472      1870.00
473          NaN
474      1744.00
475      1741.00
476          NaN
477      1980.00
478      2802.00
479          NaN
480      1930.00
481          NaN
482          NaN
483          NaN
484      2250.00
485          NaN
486      1760.00
487      1837.00
488          NaN
489      1970.00
490          NaN
491          NaN
492          NaN
493          NaN
494      1741.00
495      1818.00
496      1270.00
497          NaN
498          NaN
499      1479.00
500      1650.00
501          NaN
502      2812.00
503          NaN
504          NaN
505          NaN
506      1550.00
507          NaN
508      1995.00
509      1975.00
510      2025.00
511          NaN
512          NaN
513      1264.00
514          NaN
515      2355.00
516          NaN
517          NaN
518          NaN
519          NaN
520          NaN
521      1654.00
522          NaN
523          NaN
524      2103.00
525          NaN
526      2997.00
527      2598.00
528      1081.00
529      1850.00
530          NaN
531          NaN
532          NaN
533          NaN
534          NaN
535          NaN
536      2100.00
537      1929.00
538      1950.00
539      1406.00
540      2350.00
541          NaN
542          NaN
543          NaN
544          NaN
545          NaN
546      2290.00
547      1930.00
548      1350.00
549          NaN
550          NaN
551          NaN
552      2042.00
553          NaN
554      1950.00
555      2003.00
556      2364.00
557          NaN
558      1997.00
559          NaN
560      2403.00
561          NaN
562      2364.00
563      2250.00
564          NaN
565       602.00
566      1500.00
567          NaN
568      1400.00
569      1650.00
570       553.00
571          NaN
572          NaN
573          NaN
574          NaN
575      1844.00
576      1717.00
577          NaN
578          NaN
579          NaN
580          NaN
581      1760.00
582          NaN
583          NaN
584      2358.00
585          NaN
586      2812.00
587          NaN
588      1650.00
589      1205.00
590          NaN
591          NaN
592      1929.00
593       850.00
594          NaN
595      2250.00
596          NaN
597      1103.00
598          NaN
599       650.00
600      3250.00
601          NaN
602      1950.00
603          NaN
604       925.00
605          NaN
606      1990.00
607          NaN
608      3363.00
609      1300.00
610          NaN
611          NaN
612      2812.00
613      2361.00
614      2215.00
615          NaN
616          NaN
617          NaN
618          NaN
619          NaN
620      1758.00
621      1320.00
622          NaN
623      2000.00
624          NaN
625      1295.00
626          NaN
627          NaN
628      1326.00
629          NaN
630      1364.00
631      1395.00
632      1850.00
633          NaN
634          NaN
635          NaN
636          NaN
637          NaN
638          NaN
639      1640.00
640          NaN
641          NaN
642          NaN
643      1689.00
644          NaN
645          NaN
646      2350.00
647          NaN
648          NaN
649      1960.00
650      1850.00
651          NaN
652      1200.00
653      2690.00
654          NaN
655          NaN
656      2355.00
657          NaN
658      1630.00
659      1920.00
660      1215.00
661          NaN
662          NaN
663          NaN
664      1245.00
665       406.00
666      2325.00
667      5514.00
668          NaN
669      3090.00
670      1366.00
671      1640.00
672       602.00
673      2600.00
674       990.00
675      1828.00
676      1534.00
677      2764.00
678          NaN
679          NaN
680          NaN
681          NaN
682          NaN
683          NaN
684      1921.00
685          NaN
686          NaN
687          NaN
688          NaN
689      1889.00
690      2000.00
691          NaN
692      2800.00
693      1760.00
694          NaN
695          NaN
696          NaN
697          NaN
698      3000.00
699       553.00
700          NaN
701          NaN
702      1815.00
703      2000.00
704      2450.00
705      2727.00
706          NaN
707          NaN
708          NaN
709          NaN
710      1750.00
711      1640.00
712      1000.00
713      1300.00
714      1790.00
715      1640.00
716      1640.00
717      1950.00
718          NaN
719      1930.00
720          NaN
721      1350.00
722          NaN
723          NaN
724      1385.00
725          NaN
726      1475.00
727      1250.00
728          NaN
729          NaN
730      2150.00
731          NaN
732          NaN
733      1942.00
734      1720.00
735          NaN
736      3000.00
737          NaN
738      1640.00
739      1578.00
740      1689.00
741      1425.00
742      6000.00
743      3400.00
744          NaN
745      1950.00
746      2670.00
747      1275.00
748          NaN
749          NaN
750      1261.00
751      2802.00
752          NaN
753          NaN
754      1943.00
755          NaN
756          NaN
757      1245.00
758      1640.00
759          NaN
760      1975.00
761      2000.00
762          NaN
763      1920.00
764       700.00
765      1385.00
766      2103.00
767      2800.00
768          NaN
769      1100.00
770      1457.00
771          NaN
772      1929.00
773          NaN
774          NaN
775          NaN
776      1380.00
777          NaN
778          NaN
779          NaN
780          NaN
781      1608.00
782      3434.00
783          NaN
784      1505.00
785          NaN
786          NaN
787          NaN
788          NaN
789      1020.00
790          NaN
791          NaN
792      1758.00
793          NaN
794      1440.00
795      1572.00
796          NaN
797      1991.00
798      1150.00
799          NaN
800          NaN
801          NaN
802          NaN
803      2150.00
804      2812.00
805          NaN
806      1610.00
807          NaN
808      1500.00
809      3150.00
810      1215.00
811          NaN
812      1269.00
813      2090.00
814      1990.00
815      2150.00
816          NaN
817      2025.00
818      1252.13
819          NaN
820          NaN
821          NaN
822          NaN
823          NaN
824          NaN
825      2875.00
826      1400.00
827          NaN
828      1360.00
829          NaN
830          NaN
831          NaN
832          NaN
833      2149.00
834       602.00
835      2441.00
836          NaN
837          NaN
838      1510.00
839          NaN
840      3055.00
841          NaN
842      1380.00
843      2727.00
844      1578.00
845      1628.00
846          NaN
847      1361.00
848          NaN
849      1920.00
850          NaN
851          NaN
852      1366.00
853      2010.00
854          NaN
855      2103.00
856      1983.00
857          NaN
858      1415.00
859      1650.00
860          NaN
861      2150.00
862          NaN
863          NaN
864      1750.00
865          NaN
866          NaN
867      1520.00
868      3390.00
869      1920.00
870      1650.00
871          NaN
872       340.00
873          NaN
874          NaN
875          NaN
876      4690.00
877      1481.00
878          NaN
879      2191.00
880          NaN
881      1880.00
882          NaN
883      1950.00
884          NaN
885          NaN
886          NaN
887          NaN
888      2289.00
889      2600.00
890      1250.00
891          NaN
892          NaN
893      1430.00
894      1900.00
895      2191.00
896      4337.00
897      1350.00
898      1650.00
899          NaN
900          NaN
901      2660.00
902      2605.00
903          NaN
904      2390.00
905      1565.00
906      1580.00
907       735.00
908      2025.00
909          NaN
910          NaN
911          NaN
912          NaN
913      1960.00
914          NaN
915          NaN
916          NaN
917      1690.00
918          NaN
919          NaN
920          NaN
921          NaN
922      1579.00
923          NaN
924       735.00
925      2812.00
926          NaN
927      1260.00
928          NaN
929      1950.00
930      1400.00
931          NaN
932          NaN
933          NaN
934          NaN
935          NaN
936          NaN
937          NaN
938      1976.00
939      4400.00
940      3400.00
941          NaN
942      2132.00
943      2408.00
944      2305.00
945      1452.00
946          NaN
947      1350.00
948          NaN
949      1745.00
950          NaN
951      2200.00
952          NaN
953          NaN
954          NaN
955      1850.00
956      2400.00
957      1900.00
958      1875.00
959      1875.00
960      1940.00
961          NaN
962      2862.00
963          NaN
964          NaN
965          NaN
966      1900.00
967      1415.00
968      1805.00
969          NaN
970      1772.00
971          NaN
972      4200.00
973          NaN
974      2600.00
975      2070.00
976          NaN
977          NaN
978       600.00
979      2625.00
980      1802.00
981      3150.00
982          NaN
983      2400.00
984          NaN
985      1815.00
986       145.00
987      2350.00
988      1735.00
989          NaN
990          NaN
991          NaN
992      1930.00
993          NaN
994      4350.00
995      2200.00
996          NaN
997      1110.00
998          NaN
999      1828.00
1000     1727.00
1001     1790.00
1002     2010.00
1003         NaN
1004         NaN
1005     2450.00
1006     3750.00
1007         NaN
1008         NaN
1009     1400.00
1010         NaN
1011     1485.00
1012         NaN
1013     2605.00
1014     1671.00
1015     1360.00
1016      623.00
1017         NaN
1018     2691.00
1019         NaN
1020     2364.00
1021     1578.00
1022         NaN
1023         NaN
1024         NaN
1025         NaN
1026         NaN
1027     1770.00
1028         NaN
1029     2200.00
1030     4095.00
1031     1741.00
1032     1900.00
1033         NaN
1034     2290.00
1035         NaN
1036         NaN
1037      639.00
1038     2950.00
1039         NaN
1040         NaN
1041      726.00
1042         NaN
1043     1578.00
1044         NaN
1045     1975.00
1046     2100.00
1047         NaN
1048         NaN
1049         NaN
1050         NaN
1051         NaN
1052     2361.00
1053     2077.00
1054     1067.00
1055         NaN
1056     1454.00
1057         NaN
1058         NaN
1059     1815.00
1060     2359.00
1061     2086.00
1062     2100.00
1063     2273.00
1064         NaN
1065         NaN
1066         NaN
1067         NaN
1068     2872.00
1069     2660.00
1070      845.30
1071         NaN
1072         NaN
1073         NaN
1074     1404.00
1075         NaN
1076         NaN
1077         NaN
1078     1741.00
1079     1650.00
1080         NaN
1081     1780.00
1082     1260.00
1083         NaN
1084         NaN
1085     1815.00
1086     1538.00
1087         NaN
1088         NaN
1089         NaN
1090         NaN
1091         NaN
1092         NaN
1093         NaN
1094     1812.00
1095         NaN
1096     1650.00
1097     1845.00
1098      650.00
1099         NaN
1100     1790.00
1101         NaN
1102         NaN
1103         NaN
1104         NaN
1105     2940.00
1106     3355.00
1107         NaN
1108         NaN
1109     2000.00
1110         NaN
1111         NaN
1112         NaN
1113         NaN
1114     1920.00
1115         NaN
1116         NaN
1117         NaN
1118         NaN
1119         NaN
1120     1381.00
1121     2000.00
1122         NaN
1123         NaN
1124     1995.00
1125         NaN
1126     2010.00
1127     1360.00
1128         NaN
1129     1534.00
1130         NaN
1131     2103.00
1132     1383.00
1133         NaN
1134     2150.00
1135         NaN
1136         NaN
1137     1970.00
1138         NaN
1139         NaN
1140     2020.00
1141     1457.00
1142         NaN
1143     1727.00
1144     1568.00
1145         NaN
1146     1640.00
1147         NaN
1148     1404.00
1149         NaN
1150         NaN
1151         NaN
1152     1950.00
1153         NaN
1154     1750.00
1155      510.00
1156         NaN
1157     1366.00
1158     2355.00
1159     1100.00
1160     2979.00
1161         NaN
1162         NaN
1163     1450.00
1164     2851.00
1165         NaN
1166     1352.00
1167         NaN
1168         NaN
1169         NaN
1170         NaN
1171         NaN
1172      650.00
1173         NaN
1174         NaN
1175         NaN

In [22]:
df.sample(5)[['area', 'areaWithType','super_built_up_area']]

,area,areaWithType,super_built_up_area
2612,2003.0,Super Built up area 2003(186.08 sq.m.)Built Up area: 1338.29 sq.ft. (124.33 sq.m.)Carpet area: 986.41 sq.ft. (91.64 sq.m.),2003.0
2103,1450.0,Carpet area: 1450 (134.71 sq.m.),NaN
2374,3500.0,Built Up area: 3500 (325.16 sq.m.)Carpet area: 2500 sq.ft. (232.26 sq.m.),NaN
3327,523.0,Carpet area: 523 (48.59 sq.m.),NaN
324,2018.0,Super Built up area 2018(187.48 sq.m.),2018.0

In [23]:
df[['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].sample(5)

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
1967,1.90,flat,2724.0,Super Built up area 2724(253.07 sq.m.),2724.0,NaN,NaN
942,2.40,flat,2132.0,Super Built up area 2132(198.07 sq.m.)Built Up area: 1800 sq.ft. (167.23 sq.m.)Carpet area: 1400 sq.ft. (130.06 sq.m.),2132.0,1800.0,1400.0
2768,4.75,house,4500.0,Built Up area: 4500 (418.06 sq.m.),NaN,4500.0,NaN
914,3.00,flat,2860.0,Carpet area: 2860 (265.7 sq.m.),NaN,NaN,2860.0
2255,0.95,flat,1450.0,Carpet area: 1450 (134.71 sq.m.),NaN,NaN,1450.0

In [24]:
df[~((df['super_built_up_area'].isnull()) | (df['built_up_area'].isnull()) | (df['carpet_area'].isnull()))][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].shape

(534, 7)

In [25]:
df[df['areaWithType'].str.contains('Plot')][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].sample(5)

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
1482,5.5,house,20250.0,Plot area 215(179.77 sq.m.)Built Up area: 2850 sq.yards (2382.96 sq.m.)Carpet area: 2250 sq.yards (1881.29 sq.m.),NaN,2850.0,2250.0
645,8.0,house,8287.0,Plot area 362(33.63 sq.m.)Built Up area: 8286 sq.ft. (769.79 sq.m.),NaN,8286.0,NaN
594,9.0,house,3240.0,Plot area 360(301.01 sq.m.),NaN,NaN,NaN
504,1.7,house,900.0,Plot area 900(83.61 sq.m.),NaN,NaN,NaN
1576,5.6,house,3240.0,Plot area 360(301.01 sq.m.),NaN,NaN,NaN

In [26]:
df.isnull().sum()

property_type                  0
society                        1
sector                         0
price                         17
price_per_sqft                17
area                          17
areaWithType                   0
bedRoom                        0
bathroom                       0
balcony                        0
additionalRoom                 0
floorNum                      19
facing                      1105
agePossession                  1
nearbyLocations              177
furnishDetails               980
features                     635
super_built_up_area         1887
super_built_up_area_sqft    1887
built_up_area               2615
carpet_area                 1859
dtype: int64

In [27]:
df['areaWithType'].isnull().sum()

0

In [33]:
all_nan_df = df[((df['super_built_up_area'].isnull()) & (df['built_up_area'].isnull()) & (df['carpet_area'].isnull()))][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']]

In [34]:
all_nan_df.head()

,price,property_type,area,areaWithType,super_built_up_area,built_up_area,carpet_area
4,6.00,house,2700.0,Plot area 300(250.84 sq.m.),NaN,NaN,NaN
5,4.50,house,1350.0,Plot area 150(125.42 sq.m.),NaN,NaN,NaN
11,8.90,house,2700.0,Plot area 300(250.84 sq.m.),NaN,NaN,NaN
13,0.95,house,1070.0,Plot area 1070(99.41 sq.m.),NaN,NaN,NaN
15,1.25,house,82781.0,Plot area 115(7692.86 sq.m.),NaN,NaN,NaN

In [30]:
all_nan_index = all_nan_df = df[((df['super_built_up_area'].isnull()) & (df['built_up_area'].isnull()) & (df['carpet_area'].isnull()))][['price','property_type','area','areaWithType','super_built_up_area','built_up_area','carpet_area']].index

In [31]:
# Function to extract plot area from 'areaWithType' column
def extract_plot_area(area_with_type):
    match = re.search(r'Plot area (\d+\.?\d*)', area_with_type)
    return float(match.group(1)) if match else None

In [32]:
all_nan_df['built_up_area'] = all_nan_df['areaWithType'].apply(extract_plot_area)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices