In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv('cars.csv')

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [5]:
np.random.seed(42)
missing_km_indices = np.random.choice(df.index, size=int(0.05*len(df)), replace=False)
df.loc[missing_km_indices, 'km_driven'] = np.nan

In [6]:
# Introduce missing values in 'owner' column (1% missing values)
missing_owner_indices = np.random.choice(df.index, size=int(0.01*len(df)), replace=False)
df.loc[missing_owner_indices, 'owner'] = np.nan

In [7]:
df.isnull().sum()

brand              0
km_driven        406
fuel               0
owner             81
selling_price      0
dtype: int64

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                                                      df.drop(columns=['selling_price']),
                                                      df['selling_price'],
                                                      test_size=0.2,
                                                      random_state=42
                                                    )

In [9]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata     2560.0  Petrol           First Owner
6144    Honda    80000.0  Petrol          Second Owner
6381  Hyundai   150000.0  Diesel  Fourth & Above Owner
438    Maruti   120000.0  Diesel          Second Owner
5939   Maruti    25000.0  Petrol           First Owner

In [10]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 6502 entries, 6518 to 7270
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   brand      6502 non-null   str
 1   km_driven  6502 non-null   float64
 2   fuel       6502 non-null   str
 3   owner      6442 non-null   str
dtypes: float64(1), str(3)
memory usage: 405.6 KB

## Plan of Attack

-  Missing value imputation
-  Encoding Categorical Variables
-  Scaling
-  Feature Selection
-  Model building
-  Prediction

In [11]:
df['owner'].value_counts()

owner
First Owner             5235
Second Owner            2085
Third Owner              549
Fourth & Above Owner     173
Test Drive Car             5
Name: count, dtype: int64

In [12]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest, chi2

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

In [16]:
X_train.head()

        brand  km_driven    fuel                 owner
6518     Tata     2560.0  Petrol           First Owner
6144    Honda    80000.0  Petrol          Second Owner
6381  Hyundai   150000.0  Diesel  Fourth & Above Owner
438    Maruti   120000.0  Diesel          Second Owner
5939   Maruti    25000.0  Petrol           First Owner

In [14]:
# Imputation transformer
trf1 = ColumnTransformer(
    [
        ('impute_km_driven', SimpleImputer(), [1]), 
        ('impute_owner', SimpleImputer(strategy='most_frequent'), [3])
    ], 
    remainder='passthrough'
)

In [17]:
# Encode categorical variable 
trf2 = ColumnTransformer(
    [
        ('ordinal', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), [3]), 
        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False), [0, 2])
    ], 
    remainder='passthrough'
)

In [18]:
# Scaling 
trf3 = ColumnTransformer([
    ('scale', MinMaxScaler(), slice(0, 38))
])

In [19]:
# Feature selection 
trf4 = SelectKBest(score_func=chi2,k=10)

In [20]:
# train the model
trf5 = RandomForestRegressor()

In [21]:
from sklearn.pipeline import Pipeline

pipe = Pipeline([
    ('imputer',trf1),
    ('encoder',trf2),
    ('scaler',trf3),
    ('fselector',trf4),
    ('model',trf5)
])

In [22]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('imputer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_km_driven',
                                                  SimpleImputer(), [1]),
                                                 ('impute_owner',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [3])])),
                ('encoder',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ordinal',
                                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                 unknown_value=-1),
                                                  [3]),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [0, 2])])),
                ('scaler',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 38, None))])),
                ('fselector',
                 SelectKBest(score_func=<function chi2 at 0x11dbd1b20>)),
                ('model', RandomForestRegressor())])

In [23]:
pipe.feature_names_in_

array(['brand', 'km_driven', 'fuel', 'owner'], dtype=object)

In [24]:
pipe.named_steps

{'imputer': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_km_driven', SimpleImputer(), [1]),
                                 ('impute_owner',
                                  SimpleImputer(strategy='most_frequent'),
                                  [3])]),
 'encoder': ColumnTransformer(remainder='passthrough',
                   transformers=[('ordinal',
                                  OrdinalEncoder(handle_unknown='use_encoded_value',
                                                 unknown_value=-1),
                                  [3]),
                                 ('onehot',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse_output=False),
                                  [0, 2])]),
 'scaler': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 38, None))]),
 'fselector': SelectKBest(score_func=<function chi2 at 0x11dbd1b20>),
 'model': RandomForestRegressor()}

In [25]:
pipe.named_steps['scaler'].transformers_[0][1].data_max_

array([3., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1.])

In [26]:
pipe.predict(X_test)[10:40]

array([631107.85033222, 631107.85033222, 631107.85033222, 631107.85033222,
       631107.85033222, 631107.85033222, 631107.85033222, 631107.85033222,
       631107.85033222, 631107.85033222, 631107.85033222, 631107.85033222,
       631107.85033222, 631107.85033222, 631107.85033222, 631107.85033222,
       631107.85033222, 631107.85033222, 631107.85033222, 631107.85033222,
       631107.85033222, 631107.85033222, 631107.85033222, 631107.85033222,
       631107.85033222, 631107.85033222, 631107.85033222, 631107.85033222,
       631107.85033222, 631107.85033222])

In [27]:
pipe.predict(np.array(['Maruti',100000.0,'Diesel','First Owner']).reshape(1,4))

/Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
/Users/sanjaymahto/Python/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(

array([631107.85033222])

In [28]:
# cross validation using cross_val_score
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X_train, y_train, cv=5, scoring='neg_mean_squared_error').mean()

np.float64(-639113244101.0538)

In [29]:
# gridsearchcv
params = {
    'model__max_depth':[1,2,3,4,5,None]
}

In [30]:
from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(pipe, params, cv=5, scoring='neg_mean_squared_error')
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('imputer',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_km_driven',
                                                                         SimpleImputer(),
                                                                         [1]),
                                                                        ('impute_owner',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [3])])),
                                       ('encoder',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ordinal',
                                                                         OrdinalEncoder(handle_unknown='use_encoded_value',
                                                                                        unknow...
                                                                        ('onehot',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse_output=False),
                                                                         [0,
                                                                          2])])),
                                       ('scaler',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 38, None))])),
                                       ('fselector',
                                        SelectKBest(score_func=<function chi2 at 0x11dbd1b20>)),
                                       ('model', RandomForestRegressor())]),
             param_grid={'model__max_depth': [1, 2, 3, 4, 5, None]},
             scoring='neg_mean_squared_error')

In [ ]:
# export
import pickle
pickle.dump(pipe,open('pipe.pkl','wb'))